version: '3'

services: 

  wpp-slot-1:
    image: joneco/wpp
    restart: always
    ports:
      - "8081:8080"
    environment:
      - SLOT=slot01
    volumes:
      - /storage/tokens:/usr/app/storage/tokens
    container_name: wpp-slot-1
    hostname: wppp
    entrypoint: npm run start
    networks: 
      wpp-network:
        ipv4_address: 172.20.0.2
    tty: true
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 200M
  wpp-slot-2:
    image: joneco/wpp
    restart: always
    ports:
      - "8082:8080"
    environment:
      - SLOT=slot02
    volumes:
      - /storage/tokens:/usr/app/storage/tokens
    container_name: wpp-slot-2
    hostname: wppp
    entrypoint: npm run start
    networks: 
      wpp-network:
        ipv4_address: 172.20.0.3
    tty: true
    
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 200M

  wpp-slot-3:
    image: joneco/wpp
    restart: always
    ports:
      - "8083:8080"
    environment:
      - SLOT=slot03
    volumes:
      - /storage/tokens:/usr/app/storage/tokens
    container_name: wpp-slot-3
    hostname: wppp
    entrypoint: npm run start
    networks: 
      wpp-network:
        ipv4_address: 172.20.0.4
    tty: true
    
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 200M

  wpp-slot-4:
    image: joneco/wpp
    restart: always
    ports:
      - "8084:8080"
    environment:
      - SLOT=slot04
    volumes:
      - /storage/tokens:/usr/app/storage/tokens
    container_name: wpp-slot-4
    hostname: wppp
    entrypoint: npm run start
    networks: 
      wpp-network:
        ipv4_address: 172.20.0.5
    tty: true
    
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 200M
  wpp-slot-5:
    image: joneco/wpp
    restart: always
    ports:
      - "8085:8080"
    environment:
      - SLOT=slot05
    volumes:
      - /storage/tokens:/usr/app/storage/tokens
    container_name: wpp-slot-5
    hostname: wppp
    entrypoint: npm run start
    networks: 
      wpp-network:
        ipv4_address: 172.20.0.6
    tty: true
    
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 200M

  nginx:
      image: joneco/wpp-nginx
      container_name: nginx
      hostname: nginx
      entrypoint: nginx -g "daemon off;"
      ports:
        - "80:80"
      networks: 
        wpp-network:
          ipv4_address: 172.20.0.10
      deploy:
        resources:
          limits:
            memory: 500M
          reservations:
            memory: 200M
      depends_on:
        - wpp-slot-1
        - wpp-slot-2
    
networks: 
  wpp-network:
    name: wpp-network
    driver: bridge 
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16